version: 2

## Definitions
build_allways: &build_allways
  filters:
    tags:
      only: /.*/
defaults: &defaults
  environment:
    KUBELESS_VERSION: v1.0.0-alpha.8
    MINIKUBE_VERSION: v0.25.2
run_test: &run_test
  steps:
    - checkout
    - run: make bootstrap
    - run: ./script/integration-tests.sh ${CIRCLE_JOB}

#### End of definitions

workflows:
  version: 2
  kubeless:
    jobs:
      - test:
          <<: *build_allways
jobs:
  stable/php:
    machine: true
    <<: *defaults
    <<: *run_test
