version: 2

## Definitions
defaults: &defaults
  environment:
    KUBELESS_VERSION: v1.0.0-alpha.8
    MINIKUBE_VERSION: v0.25.2
    GOPATH: /home/circleci/.go_workspace
run_test: &run_test
  steps:
    - checkout
    - run: |
        # Determine if running the tests are necessary
        if [[ -n "$CIRCLE_PULL_REQUEST" ]]; then
          # If the build is a pull request 
          # and the runtime is not affected
          # we omit the build
          if ! git diff origin/master --name-only | grep ${CIRCLE_JOB}; then
            circleci step halt
          fi
        fi
    - run: make bootstrap
    - run: ./script/integration-tests.sh ${CIRCLE_JOB}
#### End of definitions

workflows:
  version: 2
  kubeless:
    jobs:
      - stable/ballerina
      - stable/dotnetcore
      - stable/golang
      - stable/java
      - stable/nodejs
      - stable/php
      - stable/python
      - stable/ruby
      - incubator/jvm
      - incubator/nodejs_distroless
      - incubator/nodejs_ce
jobs:
  stable/ballerina:
    machine: true
    <<: *defaults
    <<: *run_test
  stable/dotnetcore:
    machine: true
    <<: *defaults
    <<: *run_test
  stable/golang:
    machine: true
    <<: *defaults
    <<: *run_test
  stable/java:
    machine: true
    <<: *defaults
    <<: *run_test
  stable/nodejs:
    machine: true
    <<: *defaults
    <<: *run_test
  stable/php:
    machine: true
    <<: *defaults
    <<: *run_test
  stable/python:
    machine: true
    <<: *defaults
    <<: *run_test
  stable/ruby:
    machine: true
    <<: *defaults
    <<: *run_test
  incubator/jvm:
    machine: true
    <<: *defaults
    <<: *run_test
  incubator/nodejs_distroless:
    machine: true
    <<: *defaults
    <<: *run_test
  incubator/nodejs_ce:
    machine: true
    <<: *defaults
    <<: *run_test
